# Generated by Django 5.0.6 on 2024-07-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='users', to='org.organisation'),
        ),
        migrations.DeleteModel(
            name='UserOrganisation',
        ),
    ]
